### ISSUE TITLE
Daemon schema should be available inside gapi-cli.conf.yml

### ISSUE THREAD

**Issue by Stradivario** [Stradivario/gapi-cli#9]
> The main idea of this feature is to create really powerful and interactive CLI

### Main functionalities

1. User will be able to add commands using Graphql Query inside gapi-cli.conf.yml
Example:

```yml
commands:
   your-cli:
     my-command: gql`query { status { status } }`
```

When executing `gapi your-cli my-command` you will get result as follow:

```typescript
{
  "data": {
    "status": {
      "status": "200"
    }
  }
}
```

2. Every Graphql API build with @gapi will have ability to create command line utility based on schema. 
3. Automatic schema introspection and build command line utility
4. Custom commands via CLI
